# 1.基本文本处理技能

###### 1.1分词的概念

        词是最小的能够独立活动的有意义的语言成分，英文单词之间以空格作为自然分界符，而汉语是以字为基本的书写单位，词语之间没有明显的区分标记，因此中文词语分析是中文信息处理的进出与关键。常见的方法有：正向最大，逆向最大、双向最大匹配法。
* 1 正向最大：从前往后取词，每次减一个字，直至词典命中或剩下1个单字。
* 2 逆向最大：从后往前取词，每次减一个字，直至词典命中或剩下1个单字。
* 3 双向最大匹配：正向最大与逆向最大两种算法都进行一遍 分词，根据词的<font color="#dd0000">**词的颗粒度越大于好**</font>且<font color="#dd0000">**单字和非字典词越少越好**</font>，进行分词。

###### 1.2 词、字符频率统计

In [45]:
'''使用Python中的collections.Counter模块'''
from collections import Counter,defaultdict
import os
filepath = 'D:/ML_Study/task_2/cnews'
with open(os.path.join(filepath,'cnewstestpart.txt'),'r',encoding='utf-8') as fp:
    file=fp.read()
    #print(document)
words_count = Counter(file)
#print(words_count)

# 2.语言模型

###### n-gram语言模型
    n-gram模型也称为n-1阶马尔科夫模型，它有有一个有限历史假设：当前词的出现概率仅仅与前面n-1个此相关： 
\begin{equation} P(s)=P(W_1,W_2,...,W_k)=\prod_{i=1}^kp(W_i|W_i-n+1,...,W_i-1) \end{equation}


###### n-gram模型的参数估计
    模型的参数估计也称为模型的训练，一般采用最大似然估计的方法对模型的参数进行估计：
$$P(W_i|W_i-n+1,\ldots,W_i-1)=\frac{C(W_i-n+1,\ldots,W_i-1,W_i)}{C(W_i-n+1,\ldots,W_i-1)}$$

In [46]:
class NGram(object):

    def __init__(self, n):
        # n is the order of n-gram language model
        self.n = n
        self.unigram = {}
        self.bigram = {}
    # caluclate the ngram of the words
    #
    # @param    words       list{str}
    # @return   none
        # scan a sentence, extract the ngram and update their
    # frequence.
    #
    # @param    sentence    list{str}
    # @return   none
    def scan(self, sentence):
        # file your code here
        for line in sentence:
            self.ngram(line.split())
        #unigram
        if self.n == 1:
            try:
                fip = open("D:/ML_Study/task_2/cnews/uni.txt","w")
            except:
                print >> sys.stderr ,"failed to open uni.txt"
            for i in self.unigram:
                fip.write("%s %d\n" % (i,self.unigram[i]))
        if self.n == 2:
            try:
                fip = open("D:/ML_Study/task_2/cnews/bi.txt","w")
            except:
                print >> sys.stderr ,"failed to open bi.txt"
            for i in self.bigram:
                fip.write("%s %d\n" % (i,self.bigram[i]))
                
    def ngram(self, words):
        # unigram
        if self.n == 1:
            for word in words:
                if word not in self.unigram:
                    self.unigram[word] = 1
                else:
                    self.unigram[word] = self.unigram[word] + 1

        # bigram
        if self.n == 2:
            num = 0
            stri = ''
            for i in words:
                num = num + 1
                if num == 2:
                    stri  = stri + " "
                stri = stri + i
                if num == 2:
                    if stri not in self.bigram:
                        self.bigram[stri] = 1
                    else:
                        self.bigram[stri] = self.bigram[stri] + 1
                    num = 0
                    stri = ''

if __name__=="__main__":
    uni = NGram(1)
    bi = NGram(2)
    uni.scan(file)
    bi.scan(file)

In [47]:
import jieba
import os

In [48]:
#filepath = 'D:/ML_Study/task_2/cnews'

In [49]:
jieba.suggest_freq('鲍勃库西', True)
# 返回的是一个迭代器，需要查看结果的话需要将其转换为list
file_cut=list(jieba.cut(file))
#print(document_cut)
uni.scan(file_cut)
bi.scan(file_cut)

In [50]:
print(result)

体育 	 鲍勃库西 奖归 谁 属 ？   NCAA 最强 控卫 是 坎巴 还是 弗神 新浪 体育讯 如今 ， 本赛季 的 NCAA 进入 到 了 末段 ， 各项 奖项 的 评选 结果 也 即将 出炉 ， 其中 评选 最佳 控卫 的 鲍勃 - 库西 奖 就 将 在 下周 最终 四强 战时 公布 ， 鲍勃 - 库西 奖是 由奈 史密斯 篮球 名人堂 提供 ， 旨在 奖励 年度 最佳 大学 控卫 。 最终 获奖 的 球员 也 即将 在 以下 几名 热门 人选 中 产生 。 〈 〈 〈   NCAA 疯狂 三月 专题 主页 上线 ， 点击 链接 查看 精彩内容 吉梅尔 - 弗雷 戴特 ， 杨百翰 大学 “ 弗神 ” 吉梅尔 - 弗雷 戴特 一直 都 备受 关注 ， 他 不仅仅 是 一名 射手 ， 他会用 “ 终结 对手 脚踝 ” 一样 的 变向 过 掉 面前 的 防守 者 ， 并且 他 可以 用 任意 一支 手 完成 得分 ， 如果 他 被 犯规 了 ， 可以 提前 把 这 两份 划入 他 的 帐 下 了 ， 因为 他 是 一名 命中率 高达 90% 的 罚球 手 。 弗雷 戴特 具有 所有 伟大 控卫 都 具备 的 一点 特质 ， 他 是 一位 赢家 也 是 一位 领导者 。 “ 他 整个 赛季 至始 至终 的 稳定 领导 着 球队 前进 ， 这是 无可比拟 的 。 ” 杨百翰 大学 主教练 戴夫 - 罗斯 称赞 道 ， “ 他 的 得分 能力 毋庸置疑 ， 但是 我 认为 他 带领 球队 获胜 的 能力 才 是 他 最 重要 的 控卫 职责 。 我们 在 主场 之外 的 比赛 ( 客场 或 中 立场 ) 共 取胜 19 场 ， 他 都 表现 的 很棒 。 ” 弗雷 戴特 能否 在 NBA 取得成功 ？ 当然 ， 但是 有 很多 专业人士 比 我们 更 有 资格 去 做出 这样 的 判断 。 “ 我 喜爱 他 。 ” 凯尔特人 主教练 多克 - 里 弗斯 说道 ， “ 他 很棒 ， 我 看过 ESPN 的 片段 剪辑 ， 从 剪辑 来看 ， 他 是 个 超级 巨星 ， 我 认为 他 很 成为 一名 优秀 的 NBA 球员 。 ” 诺兰 - 史密斯 ， 杜克大学 当 赛季 初 ， 球队 宣布 大 一天 才 控卫凯瑞 - 厄尔 文因 脚趾 的 伤病 缺席 赛季 大部分 比赛 

###### 文本矩阵化

In [52]:
import jieba
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer 
# 读取停用词
def read_stopword(filename):
    stopword = []
    fp = open(filename, 'r',encoding='utf-8')
    for line in fp.readlines():
        stopword.append(line.replace('\n', ''))
    fp.close()
    return stopword
# 切分数据，并删除停用词
def cut_data(data, stopword):
    words = []
    for content in data['content']:
        word = list(jieba.cut(content))
        for w in list(set(word) & set(stopword)):
            while w in word:
                word.remove(w)
        words.append(' '.join(word))
    data['content'] = words
    return data
# 获取单词列表
def word_list(data):
    all_word = []
    for word in data['content']:
        all_word.extend(word)
    all_word = list(set(all_word))
    return all_word
# 计算文本向量
def text_vec(data):
    count_vec = CountVectorizer(max_features=300, min_df=2)
    count_vec.fit_transform(data['content'])
    fea_vec = count_vec.transform(data['content']).toarray()
    return fea_vec

if __name__ == '__main__':
    data = pd.read_csv('D:/ML_Study/task_2/cnews/cnewstestpart.txt', names=['title', 'content'], sep='\t') 
 
    stopword = read_stopword('D:/ML_Study/task_2/cnews/cnews.vocab.txt')
    data = cut_data(data, stopword)
 
    fea_vec = text_vec(data)
    print(fea_vec)

[[ 0  0  0 ...  0  0  0]
 [ 3  0  5 ...  0 13  0]
 [ 0  0  0 ...  0  0  2]
 ...
 [ 1  0  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
